//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillDeCojones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grupo02DBEntities : DbContext
    {
        public grupo02DBEntities()
            : base("name=grupo02DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AtributoSistema> AtributoSistema { get; set; }
        public DbSet<AtributoUsuario> AtributoUsuario { get; set; }
        public DbSet<CategoriaProducto> CategoriaProducto { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<ValorAtributoSistema> ValorAtributoSistema { get; set; }
        public DbSet<ValorAtributoUsuario> ValorAtributoUsuario { get; set; }
    }
}
