//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillDeCojones
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSuscripcion
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public int Productos { get; set; }
        public int Assets { get; set; }
        public int Almacenamiento { get; set; }
        public int CategoriasProducto { get; set; }
        public int CategoriasAsset { get; set; }
        public int Relaciones { get; set; }
        public sbyte IntegracionAP { get; set; }
        public int Precio { get; set; }
        public Nullable<int> Atributos { get; set; }
    }
}
