//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillDeCojones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ValorAtributoSistema = new HashSet<ValorAtributoSistema>();
            this.ValorAtributoUsuario = new HashSet<ValorAtributoUsuario>();
            this.CategoriaProducto = new HashSet<CategoriaProducto>();
        }
    
        public string LABEL { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<ValorAtributoSistema> ValorAtributoSistema { get; set; }
        public virtual ICollection<ValorAtributoUsuario> ValorAtributoUsuario { get; set; }
        public virtual ICollection<CategoriaProducto> CategoriaProducto { get; set; }
    }
}
