//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillDeCojones
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorAtributoSistema
    {
        public byte[] VALOR { get; set; }
        public int ID_ATRIBUTOSISTEMA { get; set; }
        public int ID_PRODUCTO { get; set; }
    
        public virtual AtributoSistema AtributoSistema { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
